[versions]
ndk = "29.0.14206865"
agp = "8.13.2"
kotlin = "1.9.22"
android-compileSdk = "36"
android-targetSdk = "36"
android-minSdk = "21"
cmake = "3.22.1"
vanniktech-maven-publish = "0.36.0"

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
vanniktech-maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktech-maven-publish" }
