name: build dist

on:
  push:
  pull_request:

jobs:
  linux-build:
    name: build on linux
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: apt update
      run: |
        sudo apt-get update
    - name: set up JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
    - name: copy settings
      run: mkdir -p ~/.m2 && cp .github/workflows/m2_settings.xml ~/.m2/settings.xml
    # ONLY FOR NEW RELEASE TAGS
    - name: setup gpg necessities
      if: startsWith(github.ref, 'refs/tags/')
      run: sudo bash -c "echo '$GPG_KEY_CONTENTS' | base64 -d > $WORKSPACE/'$SIGNING_SECRET_KEY_RING_FILE'"
      env:
        WORKSPACE: ${{ github.workspace }}
        GPG_KEY_CONTENTS: ${{ secrets.GPG_KEY_CONTENTS }}
        SIGNING_SECRET_KEY_RING_FILE: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
    # ONLY FOR NEW RELEASE TAGS
    - name: rewrite publish-pom.gradle to require signing
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        sed -i "s/signing {}/signing { sign publishing.publications }/" libcxx-provider/build.gradle
    # ONLY FOR NON-RELEASES
    - name: build
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: ./gradlew --warning-mode all build
    # ONLY FOR NEW RELEASE TAGS
    - name: publish
      if: startsWith(github.ref, 'refs/tags/')
      run: ./gradlew --warning-mode all publish
      env:
        ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.SIGNING_PASSWORD }}
        ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY_CONTENTS }}
    - name: upload artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: libcxx-provider-artifacts
        path: |
          libcxx-provider/build/libs/*.jar

